THF-3-tools
Codubee/StockPickerTTH1-2-Front pull request #5
Opened 2021-07-27 18:17 UTC by GabeL-code

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]
       yes

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
     finished tools components 

* **What is the current behavior?What does the code do before you made the new changes?** 
   showed nothing 

* **What is the new behavior?**
 
   shows the tools and technology that was used in out project 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
    
none 

* **Other information**:
* none

2021-07-29 17:55 UTC, Codubee commented
For this PR to be merged you have to have made a component and then imported that component into the landing page. You can view the landing page in the main branch as an example

2021-07-29 17:56 UTC, Codubee requested changes
Left some comments for feedback

2021-07-29 17:56 UTC, Codubee commented on src/views/LandingPage.js
> +const LandingPage = (props) => {
Can you change this into a functional component rather than a constant.

2021-07-29 22:50 UTC, jazfv approved these changes

2021-07-30 02:25 UTC, sophie-th submitted a review, later dismissed

2021-08-01 00:27 UTC, jazfv submitted a review, later dismissed

2021-08-05 16:44 UTC, merged